# Name of the Event
name: Deploy to GitHub Pages

# When should it happen
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      - name: Install dependencies and build application
        run: |
          npm install
          npm run build
          pwd
          ls -alt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p deploy
          ls -alt
          cd deploy
          pwd
          git fetch
          git checkout deploy
          pwd
          ls -alt
          rm -rf ./*
          ls -alt
          cp -r ./../dist/* ./
          ls -alt
          git add --all
          git commit -m "Deploy to GitHub Pages"
          # GIT_TRACE=1 GIT_CURL_VERBOSE=1 git
          if [ -n "$(git status --porcelain)" ]; then
            git push --force "https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git" deploy:deploy
          else
            echo "No changes to deploy"
          fi
