# Name of the Event
name: Deploy to GitHub Pages

# When should it happen
on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      - name: Install dependencies and build application
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p deploy
          cp -r ./dist/* ./deploy/
          cd ./deploy/
          git init
          git checkout -B deploy
          git add --all
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git remote remove origin 2>/dev/null || true
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git push origin HEAD:deploy --force
