# Name of the Event
name: Deploy to GitHub Pages

# When should it happen
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          cp -r build/* deploy/

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Deploy to GitHub Pages
        run: |
          cd deploy
          git init
          git checkout -b deploy
          git add .
          git commit -m "Deploy to GitHub Pages"
          # GIT_TRACE=1 GIT_CURL_VERBOSE=1 git 
          git remote add origin "https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"
          echo "git remote added"
          git push origin --delete deploy
          echo "deleted remote git deploy branch"
          git push --set-upstream origin deploy
          echo "pushed to remote git"

      - name: Activate Github Pages
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source": {"branch": "deploy", "path": "/"}}'
          echo "deployed"
